<?php

namespace QABundle\Repository;

/**
 * QAListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QAListRepository extends \Doctrine\ORM\EntityRepository
{
}
