<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function findSiteIdsById($categoryId){
        $ids = [];
        $categories = $this->findBy([
                "id" => $categoryId
            ]);
        foreach ( $categories as $category){
            foreach ($category->getSites() as $item ){
                $ids[] = $item->getId();
            }
        }

        return $ids;
    }
}
