<?php

namespace AppBundle\Repository;

/**
 * EmpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpRepository extends \Doctrine\ORM\EntityRepository
{
}
