<?php

namespace AppBundle\Repository;
use Knp\Component\Pager\Paginator;
use Symfony\Component\HttpFoundation\Request;

/**
 * InformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InformationRepository extends \Doctrine\ORM\EntityRepository
{
    protected $params = [];

    protected function setParams($key, $val){
        $this->params[$key] = $val;
    }

    protected function _findByDQL(Request $request,array $order=[]){

        $dql = "SELECT i FROM AppBundle:Information i ".
               " JOIN AppBundle:Site s ".
               " WHERE i.siteId = s.id ".
               " AND 1 = 1 ";
        /*************************条件查询start*****************************/
        $date = $request->request->get('date') ? $request->request->get('date') : date('Y-m-d');
        $date = new \DateTime($date);
        $dql .= " AND i.getDate = '{$date->format('Y-m-d')}' ";

        if($request->request->get("sites")){
            $dql .= " AND s.id IN ( {$request->request->get("sites")} ) ";
        }

        if($request->request->get("categories")){
            $dql .= " AND s.categoryId In ({$request->request->get("categories")} )";
        }
        /*************************条件查询end*****************************/

        //排序
        if($order){
            $dql .= " ORDER BY ".key($order). " ".$order[key($order)];
        }else{
            $dql .= " ORDER BY i.id DESC";
        }

        return $dql;
    }

    public function findByCondition(Request $request, array $order){
        $dql   = $this->_findByDQL($request, $order);
        $result = $this->getEntityManager()
            ->createQuery($dql)
            ->setParameters($this->params)
            ->getResult();
        return $result;
    }

    protected function _getPage($request){
        return $request->attributes->get('page') ? $request->attributes->get('page') : 1;
    }
    public function findByPage(Paginator $paginator, Request $request){

        $dql   = $this->_findByDQL($request);
        $query = $this->getEntityManager()->createQuery($dql)->setParameters($this->params);

        //分页
        $pagination = $paginator->paginate(
            $query,
            $request->query->get('page', $this->_getPage($request))/*page number*/,
            10/*limit per page*/
        );
        return $pagination;
    }

}
