<?php

namespace AppBundle\Repository;

/**
 * MailLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailLogRepository extends \Doctrine\ORM\EntityRepository
{
}
