CompaniesBundle\Entity\CategoryTypeData:
    type: entity
    table: category_type_data
    id:
        categoryTypeId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: category_type_id
        languageId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: language_id
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
