CompaniesBundle\Entity\Category:
    type: entity
    table: category
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        parentId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: parent_id
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        orderNum:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: order_num
        categoryTypeId:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '0'
            column: category_type_id
    lifecycleCallbacks: {  }
