CompaniesBundle\Entity\CategoryData:
    type: entity
    table: category_data
    id:
        categoryId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: category_id
        languageId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: language_id
    fields:
        name:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
    lifecycleCallbacks: {  }
