CompaniesBundle\Entity\Claim:
    type: entity
    table: claim
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: user_id
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: company_id
        licenseUrl:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: license_url
        linkUser:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: link_user
        telphone:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        addtime:
            type: datetime
            nullable: true
        status:
            type: integer
            nullable: true
            options:
                unsigned: false
                comment: 1：未处理(默认)，2：已处理(通过)，3：已处理(拒绝)，0：删除
                default: '1'
        sex:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '1'
        result:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        claimtime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
