CompaniesBundle\Entity\CompanyStat:
    type: entity
    table: company_stat
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: company_id
        ip:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        addtime:
            type: datetime
            nullable: true
        url:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        useragent:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        referer:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        userId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_id
    lifecycleCallbacks: {  }
