CompaniesBundle\Entity\Company:
    type: entity
    table: company
    indexes:
        IDX_STATUS_CAPITAL:
            columns:
                - status
                - capital
        IDX_CAPITAL:
            columns:
                - capital
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        defaultLangId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: default_lang_id
        areaId1:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: area_id1
        areaId2:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: area_id2
        areaId3:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: area_id3
        addtime:
            type: datetime
            nullable: false
        modtime:
            type: datetime
            nullable: true
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
        logo:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        license:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        licenseStatus:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: license_status
        licenseResult:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: license_result
        capital:
            type: integer
            nullable: true
            options:
                unsigned: false
        scale:
            type: integer
            nullable: true
            options:
                unsigned: false
        userMode:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: user_mode
        collectRank:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: collect_rank
        lastActiveTime:
            type: datetime
            nullable: true
            column: last_active_time
        licenseRank:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: license_rank
        checktime:
            type: datetime
            nullable: true
        remark:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        languageRank1:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: language_rank_1
        languageRank2:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: language_rank_2
        languageInfo1:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: language_info_1
        languageInfo2:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
            column: language_info_2
        vip:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: '0,不是，1：是'
                default: '0'
        vipStartdate:
            type: datetime
            nullable: true
            column: vip_startdate
        vipEnddate:
            type: datetime
            nullable: true
            column: vip_enddate
    lifecycleCallbacks: {  }
