CompaniesBundle\Entity\CompanyTag:
    type: entity
    table: company_tag
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: company_id
        tagId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: tag_id
        rank:
            type: integer
            nullable: false
            options:
                unsigned: false
    lifecycleCallbacks: {  }
