CompaniesBundle\Entity\CompanyData:
    type: entity
    table: company_data
    id:
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: company_id
        languageId:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: language_id
    fields:
        name:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
        telphone:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        tax:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        address:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        business:
            type: string
            nullable: true
            length: 1500
            options:
                fixed: false
        description:
            type: string
            nullable: true
            length: 1500
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        website:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        linkUser:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: link_user
        linkTel:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: link_tel
        linkEmail:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
            column: link_email
        linkAddress:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: link_address
        rank:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
        info:
            type: integer
            nullable: true
            options:
                unsigned: false
                default: '0'
    lifecycleCallbacks: {  }
