CompaniesBundle\Entity\Correction:
    type: entity
    table: correction
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_id
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: company_id
        contact:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        content:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        addtime:
            type: datetime
            nullable: true
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                default: '1'
    lifecycleCallbacks: {  }
