CompaniesBundle\Entity\CrmCustomers:
    type: entity
    table: crm_customers
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: company_name
        business:
            type: string
            nullable: true
            length: 1500
            options:
                fixed: false
        name:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        email:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        phone:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        note:
            type: string
            nullable: true
            length: 400
            options:
                fixed: false
        createtime:
            type: datetime
            nullable: true
        companyType:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: company_type
        companyOverseasAbility:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: company_overseas_ability
        companyScale:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: company_scale
        companyCapital:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: company_capital
    lifecycleCallbacks: {  }
