CompaniesBundle\Entity\CrmLinkedin:
    type: entity
    table: crm_linkedin
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: true
            options:
                unsigned: false
        cid:
            type: integer
            nullable: true
            options:
                unsigned: false
    lifecycleCallbacks: {  }
