CompaniesBundle\Entity\Log:
    type: entity
    table: log
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        userid:
            type: integer
            nullable: true
            options:
                unsigned: false
        opType:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: op_type
        opContent:
            type: string
            nullable: true
            length: 400
            options:
                fixed: false
            column: op_content
        addtime:
            type: datetime
            nullable: true
        ip:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
