CompaniesBundle\Entity\Node:
    type: entity
    table: node
    indexes:
        level:
            columns:
                - level
        pid:
            columns:
                - pid
        status:
            columns:
                - status
        name:
            columns:
                - name
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        title:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        status:
            type: boolean
            nullable: true
            options:
                default: '0'
        remark:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        sort:
            type: integer
            nullable: true
            options:
                unsigned: true
        pid:
            type: smallint
            nullable: false
            options:
                unsigned: true
        level:
            type: boolean
            nullable: false
    lifecycleCallbacks: {  }
