CompaniesBundle\Entity\QuotationItem:
    type: entity
    table: quotation_item
    uniqueConstraints:
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        qid:
            type: integer
            nullable: true
            options:
                unsigned: false
        name:
            type: string
            nullable: true
            length: 400
            options:
                fixed: false
        qty:
            type: integer
            nullable: true
            options:
                unsigned: false
        price:
            type: decimal
            nullable: true
            precision: 20
            scale: 2
        discount:
            type: decimal
            nullable: true
            precision: 20
            scale: 2
        amount:
            type: decimal
            nullable: true
            precision: 20
            scale: 2
    lifecycleCallbacks: {  }
