CompaniesBundle\Entity\Quotation:
    type: entity
    table: quotation
    indexes:
        date:
            columns:
                - date
        id:
            columns:
                - id
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uuid:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        uid:
            type: integer
            nullable: true
            options:
                unsigned: false
        title:
            type: string
            nullable: true
            length: 400
            options:
                fixed: false
        'no':
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        noLabel:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: no_label
        date:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        dateLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: date_label
        duedate:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
        duedateLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: duedate_label
        companyName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: company_name
        companyAddress:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: company_address
        companyRegion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: company_region
        companyCountry:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: company_country
        toCompanyName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: to_company_name
        toCompanyAddress:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: to_company_address
        toCompanyRegion:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: to_company_region
        toCompanyCountry:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
                default: ''
            column: to_company_country
        total:
            type: decimal
            nullable: true
            precision: 20
            scale: 2
        totalLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: total_label
        adjust:
            type: decimal
            nullable: true
            precision: 10
            scale: 2
        adjustLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: adjust_label
        priceUnit:
            type: string
            nullable: true
            length: 20
            options:
                fixed: false
            column: price_unit
        itemTitleLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: item_title_label
        itemQtyLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: item_qty_label
        itemPriceLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: item_price_label
        itemDiscountLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: item_discount_label
        itemAmountLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: item_amount_label
        note:
            type: string
            nullable: true
            length: 400
            options:
                fixed: false
        noteLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: note_label
        termsConditionsDesc:
            type: string
            nullable: true
            length: 800
            options:
                fixed: false
            column: terms_conditions_desc
        termsConditionsDescLabel:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: terms_conditions_desc_label
        createtime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
