CompaniesBundle\Entity\Require:
    type: entity
    table: require
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        uid:
            type: integer
            nullable: true
            options:
                unsigned: false
        name:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        type:
            type: integer
            nullable: true
            options:
                unsigned: false
        desc:
            type: string
            nullable: true
            length: 500
            options:
                fixed: false
        attachments:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
        deadline:
            type: datetime
            nullable: true
        areaId1:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: area_id1
        areaId2:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: area_id2
        companyName:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
            column: company_name
        linkman:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        linkphone:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        linkemail:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        status:
            type: integer
            nullable: true
            options:
                unsigned: false
        createtime:
            type: datetime
            nullable: true
    lifecycleCallbacks: {  }
