CompaniesBundle\Entity\Role:
    type: entity
    table: role
    indexes:
        pid:
            columns:
                - pid
        status:
            columns:
                - status
    id:
        id:
            type: smallint
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        pid:
            type: smallint
            nullable: true
            options:
                unsigned: false
        status:
            type: boolean
            nullable: true
        remark:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
