CompaniesBundle\Entity\Search:
    type: entity
    table: search
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        tagId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: tag_id
        keyword:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
        result:
            type: integer
            nullable: true
            options:
                unsigned: false
        userId:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: user_id
        addtime:
            type: datetime
            nullable: true
        ip:
            type: string
            nullable: true
            length: 100
            options:
                fixed: false
    lifecycleCallbacks: {  }
