CompaniesBundle\Entity\SgsVerify:
    type: entity
    table: sgs_verify
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: company_id
        serialno:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        auditDate:
            type: datetime
            nullable: false
            column: audit_date
        information:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
        reportUrl:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: report_url
        addDate:
            type: datetime
            nullable: true
            column: add_date
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: 1：未处理(默认)，2：已处理(通过)，3：已处理(拒绝)，0：删除
                default: '1'
        checkDate:
            type: datetime
            nullable: true
            column: check_date
        checkUser:
            type: integer
            nullable: true
            options:
                unsigned: false
            column: check_user
    lifecycleCallbacks: {  }
