CompaniesBundle\Entity\Titem:
    type: entity
    table: titem
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        companyId:
            type: integer
            nullable: false
            options:
                unsigned: false
            column: company_id
        title:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
        url:
            type: string
            nullable: true
            length: 1000
            options:
                fixed: false
        date:
            type: date
            nullable: true
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: '1:正常，0:删除'
                default: '1'
    lifecycleCallbacks: {  }
