CompaniesBundle\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        email:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
        qq:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        mobile:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
        utype:
            type: smallint
            nullable: false
            options:
                unsigned: false
                comment: "0=普通用户\r\n1=管理员"
                default: '0'
        status:
            type: integer
            nullable: false
            options:
                unsigned: false
                comment: "1=可用\r\n0=不可用"
                default: '1'
        registertime:
            type: datetime
            nullable: false
    lifecycleCallbacks: {  }
