<?php

namespace ReportBundle\Repository;
use Knp\Component\Pager\Paginator;
use ReportBundle\Entity\Report;

/**
 * ReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReportRepository extends \Doctrine\ORM\EntityRepository
{
    private $params = [];
    public function _dql(array $criteria, $orderBy=[]){

        $dql = "SELECT r, cn
                FROM ReportBundle:Report AS r
                JOIN  r.channel AS cn 
                JOIN cn.category AS c
                WHERE 1=1 ";
        if(isset($criteria["cnCategory"]) && $criteria["cnCategory"]){
            $dql .= " AND (cn.category = :cnCategory OR c.parent = :cnCategory )";
            $this->params["cnCategory"] = $criteria["cnCategory"];
        }
        if( isset($criteria["cnSite"]) && $criteria["cnSite"] ){
            $dql .= " AND cn.site = :cnSite ";
            $this->params["cnSite"] = $criteria["cnSite"];
        }
        $dql .= "ORDER BY ";
        if($orderBy){
            foreach ($orderBy as $key=>$value){
                $dql .= $key.' '.$value.',';
            }
            $dql = substr($dql, 0, -1);
        }else{
            $dql .= "r.id DESC";
        }
        return $dql;
    }
    public function findByPage(Paginator $paginator, $criteria){

        $query = $this->getEntityManager()
            ->createQuery($this->_dql($criteria))
            ->setParameters($this->params);

        return $paginator->paginate(
            $query,
            $criteria["page"],
            Report::NUM_ITEMS
        );
    }
}
