<?php

namespace SABundle\Repository;

/**
 * GrabFieldsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrabFieldsRepository extends \Doctrine\ORM\EntityRepository
{
}
