<?php

namespace SABundle\Repository;
use ReportBundle\Entity\Channel;
use ReportBundle\Entity\Report;
use SABundle\Entity\GrabRule;
use Symfony\Component\HttpFoundation\Request;

/**
 * GrabDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrabDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestGrabData(GrabRule $grabRule, $limit=5){
        $latest = $this->findBy([
            "grabRuleId" => $grabRule->getId(),
        ],["id"=>"DESC"],$limit>=5 ? 5 : $limit);
        return $latest;
    }

    public function findReportData(Report $lastReport=null){
        $params = [];
        $dql = "SELECT gr, gd
                FROM SABundle:GrabData AS gd 
                JOIN gd.grabRule AS gr 
                WHERE 1=1 ";
        $dql .= "AND gr.entity = :channel";
        $params["channel"] = Channel::LOGIC_NAME;
        if($lastReport){
            $dql .= " AND gd.createDate > :gdCreateDate ";
            $params["gdCreateDate"] = $lastReport->getGetAt()->format("Y-m-d");
        }

        return $this->getEntityManager()
            ->createQuery($dql)
            ->setParameters($params)
            ->getResult();
    }
}
