<?php

namespace SABundle\Repository;
use SABundle\Entity\GrabRule;

/**
 * GrabDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrabDataRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestGrabData(GrabRule $grabRule, $limit=5){
        $latest = $this->findBy([
            "grabRuleId" => $grabRule->getId(),
        ],["id"=>"DESC"],$limit>=5 ? 5 : $limit);
        return $latest;
    }
}
