<?php

namespace ZhanhuiBundle\Repository;

/**
 * ChannelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChannelRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForPush(){
        $channels = $this->findBy([
            "status" => true,
        ]);
        $entities = [];
        foreach ($channels as $key => $channel){
            $entities[$channel->getId()] = $channel;
        }
        return $entities;
    }
}
