<?php

namespace WordPressBundle\Repository;

/**
 * AreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TitemRepository extends \Doctrine\ORM\EntityRepository
{
}
